import { Injectable } from '@angular/core';
import * as Phoenix from '@lenovo/tan-client-bridge';
import { CPUOCStatus } from 'src/app/data-models/gaming/cpu-overclock-status.model';

@Injectable({
	providedIn: 'root'
})
export abstract class BaseVantageShellService {
	abstract registerEvent(eventType: any, handler: any);
	abstract unRegisterEvent(eventType: any, handler: any);
	abstract getLenovoId(): any;
	abstract getDashboard(): any;
	abstract getDevice(): any;
	abstract getSysinfo(): any;
	abstract getWarranty(): any;
	abstract getShellVersion(): string;
	abstract getMetrics(): any;
	abstract getMetricsPolicy(callback);
	abstract getModernPreload(): any;
	abstract getAdPolicy(): any;
	abstract getSystemUpdate(): any;
	abstract getSecurityAdvisor(): Phoenix.SecurityAdvisor;
	abstract getPermission(): any;
	abstract getConnectedHomeSecurity(): Phoenix.ConnectedHomeSecurity;
	abstract getDevicePosture(): Phoenix.DevicePosture;
	abstract getDolbySettings(): any;
	abstract getMicrophoneSettings(): any;
	abstract getSmartSettings(): any;
	abstract getBatteryInfo(): any;
	abstract getEyeCareMode(): any;
	abstract getPrivacyGuardObject(): any;
	abstract getCameraPrivacy(): any;
	abstract getCameraSettings(): any;
	abstract getVantageToolBar(): any;
	abstract getPowerIdeaNoteBook(): any;
	abstract getPowerThinkPad(): any;
	abstract getPowerItsIntelligentCooling(): any;
	abstract deviceFilter(filter);
	abstract calcDeviceFilter(filter);
	abstract getLogger(): any;
	abstract getWindows(): any;
	abstract getPrivacyCore();
	abstract getUserGuide();
	abstract generateGuid();
	abstract getCameraBlur(): any;
	abstract getCPUOCStatus(): any;
	abstract setCPUOCStatus(CpuOCStatus: CPUOCStatus): any;
	abstract getGamingAllCapabilities(): any;
	abstract getGamingLighting(): any;
	abstract getGamingOverClock(): any;
	abstract getIntelligentSensing(): any;
	abstract getMetricPreferencePlugin();
	abstract getGamingKeyLock();
	abstract getGamingHybridMode();
	abstract getGamingHwInfo();
	abstract getIntelligentMedia(): any;
	abstract getPreferenceSettings();
	abstract getNetworkBoost();
	abstract getGamingAutoClose();
	abstract setMacroKeyClear(macroKey: string): any;
	abstract getGamingMacroKey(): any;
	abstract getIntelligentCoolingForIdeaPad(): any;
	abstract macroKeyInitializeEvent(): any;
	abstract macroKeySetApplyStatus(key): any;
	abstract macroKeySetStartRecording(key): any;
	abstract macroKeySetStopRecording(key, isSuccess, message): any;
	abstract macroKeySetKey(key): any;
	abstract macroKeyClearKey(key): any;
	abstract macroKeySetRepeat(key, repeat): any;
	abstract macroKeySetInterval(key, interval): any;
	abstract macroKeySetMacroKey(key, inputs): any;
	abstract getGamingThermalMode(): any;
	abstract getImcHelper(): any;
	abstract getActiveProtectionSystem(): any;
	abstract getKeyboardManagerObject(): any;
	abstract getLenovoVoice(): any;
	abstract getOledSettings(): any;
	abstract getVersion(): any;
	abstract getVantageStub(): any;
	abstract getBetaUser(): any;
	abstract getHardwareScan(): any;
	abstract getMouseAndTouchPad(): any;
}
