export const smbMachines = {
    colorCalibration:[
        'thinkbook16pgen2'
    ],
    creatorSettings:[
        'thinkbook16pgen2',
        'thinkbook14pgen2'
    ],
    easyRendering:[
        'thinkbook16pgen2',
        'thinkbook14pgen2'
	],
	smartAppearance:[
		'thinkbookplusgen2',
		'thinkbook13x',
		'thinkbook14pgen2',
		'thinkbook16pgen2'
	]
};