/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AbTestsConfig {
  avaliableOptions?: {
    colorButton?: ColorButton;
    colorLink?: ColorLink;
  };
  abTestsName?: AbTestsName;
}

export enum ColorButton {
  A = "A",
  B = "B",
  C = "C"
}
export enum ColorLink {
  A = "A",
  B = "B"
}
export enum AbTestsName {
  colorButton = "colorButton",
  colorLink = "colorLink"
}
