export enum AppsForYouEnum {
	GetAppDetailsRespond = '[AppsForYou] GetAppDetailsRespond',
	InstallAppProgress = '[AppsForYou] InstallAppProgress',
	InstallAppResult = '[AppsForYou] InstallAppResult',
	CommonException = '[AppsForYou] CommonException',
	InstallationCancelled = '[AppsForYou] InstallationCancelled',
	StatusInstalled = 'installed',
	StatusNotInstalled = 'not installed',
	StatusDownloaded = 'downloaded',
	StatusDownloading = 'downloading',
	StatusInstalling = 'installing',
	AppGuidLenovoMigrationAssistant = 'FCF9F618-10F4-4230-99DD-F9B1CCB316AF',
	AppSiteCoreIdLenovoMigrationAssistant = '030B3E7E-9235-4A44-823A-8D02B7A6F30F',
	AppGuidAdobeCreativeCloud = '1430171F-68BC-4920-9D6B-90C73B949914',
	AppSiteCoreIdAdobeCreativeCloud = 'CBBC51B3-ABDD-475E-9C87-55226D6AAD35',
	AppSiteCoreIdAdobeCreativeCloudSMB = 'B4303CDA-E612-4798-8D09-583C9CFFFDF1',
	SeeMoreUrlAdobeCreativeCloud = 'https://www.adobepartneroffer.com/[SerialNumber]',
	AppTypeDesktop = 'Desktop App',
	AppTypeWindowStore = 'Windows Store App',
	AppTypeWeb = 'Web App',
	AdobeFamilyNameFilter = 'Yoga A940-27ICB'
}
