export enum SessionStorageKey {
	DashboardCameraPrivacy = '[SessionStorageKey] DashboardCameraPrivacy',
	DashboardEyeCareMode = '[SessionStorageKey] DashboardEyeCareMode',
	DashboardMicrophone = '[SessionStorageKey] DashboardMicrophone',
	DashboardInDashboardPage = '[SessionStorageKey] DashboardInDashboardPage',
	AvailableUpdates = '[SessionStorageKey] AvailableUpdates',
	SecurityWifiSecurityLocationFlag = '[SessionStorageKey] SecurityWifiSecurityLocationFlag',
	SecurityWifiSecurityInWifiPage = '[SessionStorageKey] SecurityWifiSecurityInWifiPage',
	SecurityWifiSecurityShowPluginMissingDialog = '[SessionStorageKey] SecurityWifiSecurityShowPluginMissingDialog',
	SecurityWifiSecurityShowHistoryNum = '[SessionStorageKey] SecurityWifiSecurityShowHistoryNum',
	SecurityWifiSecurityIsGetDevicePosture = '[SessionStorageKey] SecurityWifiSecurityIsGetDevicePosture',
	HomeProtectionInCHSPage = '[SessionStorageKey] HomeProtectionInCHSPage',
	HomeSecurityShowPluginMissingDialog = '[SessionStorageKey] HomeSecurityShowPluginMissingDialog',
	HomeSecurityShowWelcomeDialog = '[SessionStorageKey] HomeSecurityShowWelcomeDialog',
	HomeSecurityShowLocationPermisisonDialog = '[SessionStorageKey] HomeSecurityShowLocationPermisisonDialog',
	WidgetWifiStatus = '[SessionStorageKey] WidgetWifiStatus',
	ChsLocationDialogNextShowFlag = '[SessionStorageKey] ChsLocationDialogNextShowFlag',
	ChsIsGetDevicePosture = '[SessionStorageKey] ChsIsGetDevicePosture'
}
