export enum SPCategory{
    TUNEUPPERFORMANCE = 'Tune up performance',
    INTERNETPERFORMANCE = 'Internet performance',
    MALWARESECURITY = 'Malware & Security'
}

export enum SPSubCategory{
    HUNDEREAD = '100',
    HUNDEREADANDONE = '101',
    HUNDEREADANDTWO = '102',
    HUNDEREADANDTHREE = '103',
    HUNDEREADANDFOUR = '104',
    HUNDEREADANDFIVE = '105',
    TWOHUNDEREAD = '200',
    TWOHUNDEREADANDONE = '201',
    TWOHUNDEREADANDTWO = '202',
    TWOHUNDEREADANDTHREE = '203',
    TWOHUNDEREADANDFOUR = '204',
    TWOHUNDEREADANDFIVE = '205',
    THREEHUNDEREAD = '300',
    THREEHUNDEREADANDONE = '301',
    THREEHUNDEREADANDTWO = '302',
    THREEHUNDEREADANDTHREE = '303',
    THREEHUNDEREADANDFOUR = '304',
    THREEHUNDEREADANDFIVE = '305',
}